blank_issues_enabled: false
contact_links:
  - name: New BCLib Repository
    url: https://github.com/quiqueck/BCLib/issues
    about: The Issue-Tracker (and main Repository) for BCLib was moved to a new Maintainer. Please post your Issues there.